import { configureStore } from '@reduxjs/toolkit';
import postReducer from './postSlice'

// Create a store using configureStore and pass in the reducer generated by postSlice.reducer
const store = configureStore({
    reducer: {
        post: postReducer
    }
});

// Export the "addId" action creator from postSlice.actions object


// Export the store as the default export
export default store;
